Update user tools

diff --git a/src/metaswitch/crest/tools/display_user b/src/metaswitch/crest/tools/display_user
--- a/src/metaswitch/crest/tools/display_user
+++ b/src/metaswitch/crest/tools/display_user
@@ -81,6 +81,11 @@ shift
 
 HSPROV=${LOCAL_IP}:${HTTP_PORT}
 
+if [ "$(curl -s http://${HSPROV}/ping 2>&1)" != "OK" ]; then
+    printf "Error: can't contact homestead-prov @ http://${HSPROV}!\n"
+    exit 1
+fi
+
 impu=$(curl -s http://${HSPROV}/impu/sip:${USER}@${DOMAIN} 2>&1)
 if [[ ${impu:0:1} == "<" ]]; then
     if [[ "$(curl -s http://${HSPROV}/impi/${USER}@${DOMAIN}/digest)" =~ digest_ha1 ]]; then
@@ -95,7 +100,7 @@ if [[ ${impu:0:1} == "<" ]]; then
         echo "  $digest"
 	echo "iFC:"
 	(
-	    echo ${iFC}|python -c 'import xml.dom.minidom, sys; print xml.dom.minidom.parse(sys.stdin).toprettyxml()'
+	    echo ${iFC}|python -c 'import xml.dom.minidom, sys; print xml.dom.minidom.parse(sys.stdin).toprettyxml()'|sed -e '/^[[:space:]]*$/d'
 	) 2>&1 | while IFS='' read -r line; do
 	    printf "   %s\n" "$line"
 	done
diff --git a/src/metaswitch/crest/tools/update_user b/src/metaswitch/crest/tools/update_user
--- a/src/metaswitch/crest/tools/update_user
+++ b/src/metaswitch/crest/tools/update_user
@@ -8,7 +8,7 @@ cmdname=$0
 usage()
 {
     printf "\
-Usage: $cmdname [OPTION...] <directory-number> <domain>\n\
+Usage: $cmdname [OPTION...] <directory-number> <domain> <password>\n\
 \n\
 Options:\n\
   -h, --help        display this usage\n"
@@ -85,38 +85,37 @@ fi
 shift
 
 HSPROV=${LOCAL_IP}:${HTTP_PORT}
+public_id=sip:${USER}@${DOMAIN}
+private_id=${USER}@${DOMAIN}
 
-impu=$(curl -s http://${HSPROV}/impu/sip:${USER}@${DOMAIN} 2>&1)
+if [ "$(curl -s http://${HSPROV}/ping 2>&1)" != "OK" ]; then
+    printf "Error: can't contact homestead-prov @ http://${HSPROV}!\n"
+    exit 1
+fi
+
+impu=$(curl -s http://${HSPROV}/impu/${public_id} 2>&1)
 if [[ ${impu:0:1} == "<" ]]; then
-    if [[ "$(curl -s http://${HSPROV}/impi/${USER}@${DOMAIN}/digest)" =~ digest_ha1 ]]; then
-	public_id=sip:${USER}@${DOMAIN}
+    if [[ "$(curl -s http://${HSPROV}/impi/${private_id}/digest)" =~ digest_ha1 ]]; then
+	public_id=${public_id}
 
 	service_profile=$(curl -s -D - http://${HSPROV}/public/${public_id}/service_profile|grep "Location:"|awk '{print $2}'|tr '[[:space:]]' ' '|sed -e 's#[[:space:]]##g')
 	iFC=$(curl -s http://${HSPROV}${service_profile}/filter_criteria)
 
-	new_digest=$(printf "${USER}@${DOMAIN}:${DOMAIN}:${PASSWORD}"|md5sum|awk '{print $1}')
+	new_digest=$(printf "${private_id}:${DOMAIN}:${PASSWORD}"|md5sum|awk '{print $1}')
 	json_digest="{\"digest_ha1\": \"${new_digest}\", \"realm\": \"${DOMAIN}\"}"
-	put_sta=$(printf "%s\n" "${json_digest}"|curl -s curl -X PUT -d @- http://${HSPROV}/private/${USER}@${DOMAIN})
+	put_sta=$(printf "%s\n" "${json_digest}"|curl -s curl -X PUT -d @- http://${HSPROV}/private/${private_id})
 	if [ ! -z $put_sta ]; then
 	    printf "Error: couldn't update password!\n"
 	    exit 1
 	fi
-	cur_digest=$(curl -s http://${HSPROV}/private/${USER}@${DOMAIN}|python -c 'import json,sys;obj=json.load(sys.stdin);print obj["digest_ha1"]' 2>&1)
 
-	echo "HA1 digest:"
-        echo "   $cur_digest"
-	echo "iFC:"
-	(
-	    echo ${iFC}|python -c 'import xml.dom.minidom, sys; print xml.dom.minidom.parse(sys.stdin).toprettyxml()'
-	) 2>&1 | while IFS='' read -r line; do
-	    printf "   %s\n" "$line"
-	done
+	${mydir}/display_user ${USER} ${DOMAIN}
     else
-	printf "Error: no IMPI user ${USER}@${DOMAIN}\n"
+	printf "Error: no IMPI user ${private_id}\n"
 	exit 1
     fi
 else
-    printf "Error: no IMPU user 'sip:${USER}@${DOMAIN}'\n"
+    printf "Error: no IMPU user '${public_id}'\n"
     exit 1
 fi
 
