Update user commands

diff --git a/homestead.root/usr/share/clearwater/bin/assoc_user b/homestead.root/usr/share/clearwater/bin/assoc_user
--- a/homestead.root/usr/share/clearwater/bin/assoc_user
+++ b/homestead.root/usr/share/clearwater/bin/assoc_user
@@ -48,6 +48,7 @@ Usage: $cmdname [OPTION...] <directory-number>[..<directory-number>] <domain>\n\
 \n\
 Options:\n\
   --hsprov IP:PORT  IP address and port of homestead-prov\n\
+  --hs IP:PORT      IP address and port of homestead\n\
   --id IMPI-ID      IMPI ID to associate new public ID\n\
   -h, --help        display this usage\n"
 
@@ -64,7 +65,7 @@ error()
     usage
 }
 
-params="$(getopt -o h -l help,hsprov:,id: --name $cmdname -- "$@")"
+params="$(getopt -o h -l help,hsprov:,hs:,id: --name $cmdname -- "$@")"
 
 if [ $? -ne 0 ]
 then
@@ -83,6 +84,10 @@ do
 	;;
 	--hsprov)
 	export "HSPROV=${2-}"
+	shift 2
+	;;
+	--hs)
+	export "HS=${2-}"
 	shift 2
 	;;
 	--id)
@@ -149,6 +154,15 @@ fi
 shift
 
 HSPROV=${LOCAL_IP}:${HTTP_PORT}
+if [ -z $HS ]; then
+    HS=${LOCAL_IP}
+fi
+HS_IP=( $(echo $HS|sed -e 's#:# #') )
+HS=${HS_IP[0]}:8888
+if [ ! -z "${HS_IP[1]}" ]; then
+    HS=${HS_IP[0]}:${HS_IP[1]}
+fi
+
 _USERS=(${USER//,/ })
 USERS=()
 SIZES=()
@@ -218,42 +232,50 @@ while [ $i -lt ${#USERS[@]} ]; do
 	    exit 1
 	fi
 	
-	if [[ ! "$(curl -s http://${HSPROV}/impi/${private_id}/digest)" =~ digest_ha1 ]]; then
-	    if [[ $force == 0 || ( $force != 0 && $quiet == 0 ) ]]; then
-		printf "Error: IMPI user '${private_id}' does not exist!\n"
-	    fi
-	    if [ $force -eq 0 ]; then
-		exit 1
-	    fi
-	fi
+	(
+	    curl -w "\nhttp_code=%{http_code}\n" -s -X GET http://${HSPROV}/private/${private_id}; echo $? > /tmp/hsprov.sta
+	) > /tmp/hsprov.out 2>&1
+	sta=$(cat /tmp/hsprov.sta)
+	if [ $sta -eq 0 ]; then
+	    eval "$(grep "^http_code=" /tmp/hsprov.out)"
+	    if [ $http_code -ne 200 ]; then
+		if [[ $force == 0 || ( $force != 0 && $quiet == 0 ) ]]; then
+		    printf "Error: user ${public_id} does not exist!\n"
+		fi
+		if [ $force -eq 0 ]; then
+		    exit 1
+		fi
+	    else
 
-	sp_url=$(
-	    curl -s -D - http://${HSPROV}/public/sip:${private_id}/service_profile|\
-        grep "Location:"|\
-        awk '{print $2}'|\
-        sed -e 's#[[:space:]]##g'
-	)
-	#echo "sp_url=${sp_url}"
-	sp_uuid=$(echo ${sp_url}|sed -e 's#/irs/.*/service_profiles/##')
-	#echo "sp_uuid=${sp_uuid}"
-	irs_uuid=$(
-	    curl -s http://${HSPROV}/private/${private_id}/associated_implicit_registration_sets|\
-        python -c 'import json,sys;obj=json.load(sys.stdin);print obj["associated_implicit_registration_sets"][0]' 2>&1
-	)
-	#echo "irs_uuid=${irs_uuid}"
+		sp_url=$(
+		    curl -s -D - http://${HSPROV}/public/sip:${private_id}/service_profile|\
+                    grep "Location:"|\
+                    awk '{print $2}'|\
+                    sed -e 's#[[:space:]]##g'
+		)
+	        #echo "sp_url=${sp_url}"
+		sp_uuid=$(echo ${sp_url}|sed -e 's#/irs/.*/service_profiles/##')
+	        #echo "sp_uuid=${sp_uuid}"
+		irs_uuid=$(
+		    curl -s http://${HSPROV}/private/${private_id}/associated_implicit_registration_sets|\
+                    python -c 'import json,sys;obj=json.load(sys.stdin);print obj["associated_implicit_registration_sets"][0]' 2>&1
+		)
+	        #echo "irs_uuid=${irs_uuid}"
 
 	#
 	# Associate the public ID
 	#
-	#echo curl -s -X PUT -d @- http://${HSPROV}${sp_url}/public_ids/${rpublic_id}
-	pubid_sta=$(
-	    printf "<PublicIdentity><Identity>%s</Identity></PublicIdentity>\n" "${rpublic_id}"|\
-        curl -s -X PUT -d @- http://${HSPROV}${sp_url}/public_ids/${rpublic_id}
-	)
-	if [ ! -z $pubid_sta ]; then
-	    printf "Error: couldn't create public ID '${public_id}'!\n"
-	    ${mydir}/delete_user -fq ${rUSER} ${DOMAIN}
-	    exit 1
+	        #echo curl -s -X PUT -d @- http://${HSPROV}${sp_url}/public_ids/${rpublic_id}
+		pubid_sta=$(
+		    printf "<PublicIdentity><Identity>%s</Identity></PublicIdentity>\n" "${rpublic_id}"|\
+                    curl -s -X PUT -d @- http://${HSPROV}${sp_url}/public_ids/${rpublic_id}
+		)
+		if [ ! -z $pubid_sta ]; then
+		    printf "Error: couldn't create public ID '${public_id}'!\n"
+		    ${mydir}/delete_user -fq ${rUSER} ${DOMAIN}
+		    exit 1
+		fi
+	    fi
 	fi
     done
     let "i=$i + 1"
diff --git a/homestead.root/usr/share/clearwater/bin/create_user b/homestead.root/usr/share/clearwater/bin/create_user
--- a/homestead.root/usr/share/clearwater/bin/create_user
+++ b/homestead.root/usr/share/clearwater/bin/create_user
@@ -51,6 +51,7 @@ Options:\n\
   --prefix PREFIX   twin-prefix (default: 123)\n\
   --ifc iFC-FILE    XML file containing the iFC\n\
   --hsprov IP:PORT  IP address and port of homestead-prov\n\
+  --hs IP:PORT      IP address and port of homestead\n\
   -q, --quiet       don't display the user\n\
   -h, --help        display this usage\n"
 
@@ -67,7 +68,7 @@ error()
     usage
 }
 
-params="$(getopt -o hq -l help,prefix:,ifc:,quiet,hsprov:,accession --name $cmdname -- "$@")"
+params="$(getopt -o hq -l help,prefix:,ifc:,quiet,hsprov:,accession,hs: --name $cmdname -- "$@")"
 
 if [ $? -ne 0 ]
 then
@@ -86,6 +87,10 @@ do
 	;;
 	--hsprov)
 	export "HSPROV=${2-}"
+	shift 2
+	;;
+	--hs)
+	export "HS=${2-}"
 	shift 2
 	;;
 	--ifc)
@@ -181,6 +186,15 @@ print xml.dom.minidom.parse(sys.stdin).toprettyxml()\
 fi
 
 HSPROV=${LOCAL_IP}:${HTTP_PORT}
+if [ -z $HS ]; then
+    HS=${LOCAL_IP}
+fi
+HS_IP=( $(echo $HS|sed -e 's#:# #') )
+HS=${HS_IP[0]}:8888
+if [ ! -z "${HS_IP[1]}" ]; then
+    HS=${HS_IP[0]}:${HS_IP[1]}
+fi
+
 _USERS=(${USER//,/ })
 USERS=()
 SIZES=()
@@ -251,21 +265,18 @@ while [ $i -lt ${#USERS[@]} ]; do
 	    exit 1
 	fi
 
-	impu=$(curl -s http://${HSPROV}/impu/${public_id} 2>&1)
-	if [[ ${impu:0:1} == "<" ]]; then
-	    if [[ "$impu" =~ \<PrivateID\>Unspecified\</PrivateID\> ]]; then
-		printf "Warning: IMPU user '%s' already exists!\n" "${rpublic_id}"
-	    else
-		printf "Error: IMPU user '%s' already exists!\n" "${rpublic_id}"
+	(
+	    curl -w "\nhttp_code=%{http_code}\n" -s -X GET http://${HSPROV}/private/${private_id}; echo $? > /tmp/hsprov.sta
+	) > /tmp/hsprov.out 2>&1
+	sta=$(cat /tmp/hsprov.sta)
+	if [ $sta -eq 0 ]; then
+	    eval "$(grep "^http_code=" /tmp/hsprov.out)"
+	    if [ $http_code -eq 200 ]; then
+		printf "Error: user '%s' already exists!\n" "${rpublic_id}"
 		exit 1
 	    fi
 	fi
 	
-	#    if [[ "$(curl -s http://${HSPROV}/impi/${private_id}/digest)" =~ digest_ha1 ]]; then
-	#	printf "Error: IMPI user '${private_id}' already exists!\n"
-	#	exit 1
-	#    fi
-
 	#
 	# Create the private ID
 	#
@@ -447,7 +458,7 @@ EOF
 	rm -f $$.iFC*
 
 	if [ $quiet -eq 0 ];then
-	    ${mydir}/display_user ${rUSER} ${DOMAIN}
+	    ${mydir}/display_user --hs ${HS} ${rUSER} ${DOMAIN}
 	fi    
     done
     let "i=$i + 1"
diff --git a/homestead.root/usr/share/clearwater/bin/delete_user b/homestead.root/usr/share/clearwater/bin/delete_user
--- a/homestead.root/usr/share/clearwater/bin/delete_user
+++ b/homestead.root/usr/share/clearwater/bin/delete_user
@@ -48,6 +48,7 @@ Usage: $cmdname [OPTION...] <directory-number>[..<directory-number>] <domain>\n\
 \n\
 Options:\n\
   --hsprov IP:PORT  IP address and port of homestead-prov\n\
+  --hs IP:PORT      IP address and port of homestead\n\
   -f, --force       proceed with delete in the face of errors\n\
   -q, --quiet       silence 'forced' error messages and such\n\
   -h, --help        display this usage\n"
@@ -65,7 +66,7 @@ error()
     usage
 }
 
-params="$(getopt -o hfq -l help,force,quiet,hsprov: --name $cmdname -- "$@")"
+params="$(getopt -o hfq -l help,force,quiet,hsprov:,hs: --name $cmdname -- "$@")"
 
 if [ $? -ne 0 ]
 then
@@ -84,6 +85,10 @@ do
 	;;
 	--hsprov)
 	export "HSPROV=${2-}"
+	shift 2
+	;;
+	--hs)
+	export "HS=${2-}"
 	shift 2
 	;;
         -f|--force)
@@ -150,6 +155,15 @@ fi
 shift
 
 HSPROV=${LOCAL_IP}:${HTTP_PORT}
+if [ -z $HS ]; then
+    HS=${LOCAL_IP}
+fi
+HS_IP=( $(echo $HS|sed -e 's#:# #') )
+HS=${HS_IP[0]}:8888
+if [ ! -z "${HS_IP[1]}" ]; then
+    HS=${HS_IP[0]}:${HS_IP[1]}
+fi
+
 _USERS=(${USER//,/ })
 USERS=()
 SIZES=()
@@ -220,79 +234,77 @@ while [ $i -lt ${#USERS[@]} ]; do
 	    exit 1
 	fi
 
-	impu=$(curl -s http://${HSPROV}/impu/${public_id} 2>&1)
-	if [[ ${impu:0:1} != "<" ]]; then
-	    if [[ $force == 0 || ( $force != 0 && $quiet == 0 ) ]]; then
-		printf "Error: IMPU user '%s' does not exist!\n" "${rpublic_id}"
-	    fi
-	    if [ $force -eq 0 ]; then
-		exit 1
-	    fi
-	fi
-	
-	if [[ ! "$(curl -s http://${HSPROV}/impi/${private_id}/digest)" =~ digest_ha1 ]]; then
-	    if [[ $force == 0 || ( $force != 0 && $quiet == 0 ) ]]; then
-		printf "Error: IMPI user '%s' does not exist!\n" "${rprivate_id}"
-	    fi
-	    if [ $force -eq 0 ]; then
-		exit 1
-	    fi
-	fi
-
-	sp_url=$(
-	    curl -s -D - http://${HSPROV}/public/${public_id}/service_profile|\
+	(
+	    curl -w "\nhttp_code=%{http_code}\n" -s -X GET http://${HSPROV}/private/${private_id}; echo $? > /tmp/hsprov.sta
+	) > /tmp/hsprov.out 2>&1
+	sta=$(cat /tmp/hsprov.sta)
+	if [ $sta -eq 0 ]; then
+	    eval "$(grep "^http_code=" /tmp/hsprov.out)"
+	    if [ $http_code -ne 200 ]; then
+		if [[ $force == 0 || ( $force != 0 && $quiet == 0 ) ]]; then
+		    printf "Error: user ${public_id} does not exist!\n"
+		fi
+		if [ $force -eq 0 ]; then
+		    exit 1
+		fi
+	    else
+		digest=$(grep -v "^http_code=" /tmp/hsprov.out | python -c 'import json,sys;obj=json.load(sys.stdin);print obj["digest_ha1"]')
+		sp_url=$(
+		    curl -s -D - http://${HSPROV}/public/${public_id}/service_profile|\
         grep "Location:"|\
         awk '{print $2}'|\
         sed -e 's#[[:space:]]##g'
-	)
+		)
 	#echo "sp_url=${sp_url}"
-	sp_uuid=$(echo ${sp_url}|sed -e 's#/irs/.*/service_profiles/##')
+		sp_uuid=$(echo ${sp_url}|sed -e 's#/irs/.*/service_profiles/##')
 	#echo "sp_uuid=${sp_uuid}"
-	irs_uuid=$(
-	    curl -s http://${HSPROV}/private/${private_id}/associated_implicit_registration_sets|\
+		irs_uuid=$(
+		    curl -s http://${HSPROV}/private/${private_id}/associated_implicit_registration_sets|\
         python -c 'import json,sys;obj=json.load(sys.stdin);print obj["associated_implicit_registration_sets"][0]' 2>&1
-	)
+		)
 	#echo "irs_uuid=${irs_uuid}"
 
 	#
 	# Delete the public ID
 	#
-	pubid_sta=$(
-	    curl -m2 -s -X DELETE http://${HSPROV}${sp_url}/public_ids/${public_id}
-	)
-	#echo "pubid_sta=${pubid_sta}"
-	if [ ! -z "$pubid_sta" ]; then
-	    if [[ $force == 0 || ( $force != 0 && $quiet == 0 ) ]]; then
-		printf "Error: couldn't delete public ID '%s'!\n" "${rpublic_id}"
-	    fi
-	    if [ $force -eq 0 ]; then
-		exit 1
-	    fi
-	fi
+		pubid_sta=$(
+		    curl -m2 -s -X DELETE http://${HSPROV}${sp_url}/public_ids/${public_id}
+		)
+ 	    #echo "pubid_sta=${pubid_sta}"
+		if [ ! -z "$pubid_sta" ]; then
+		    if [[ $force == 0 || ( $force != 0 && $quiet == 0 ) ]]; then
+			printf "Error: couldn't delete public ID '%s'!\n" "${rpublic_id}"
+		    fi
+		    if [ $force -eq 0 ]; then
+			exit 1
+		    fi
+		fi
 
 	#
 	# Delete IRS
 	#
-	#echo curl -m2 -s -X DELETE http://${HSPROV}/irs/${irs_uuid}
-	irs_sta=$(curl -m2 -s -X DELETE http://${HSPROV}/irs/${irs_uuid})
-	#echo "irs_sta=${irs_sta}"
-	if [ ! -z "$irs_sta" ]; then
-	    if [[ $force == 0 || ( $force != 0 && $quiet == 0 ) ]]; then
-		printf "Error: couldn't delete IRS!\n"
-	    fi
-	    if [ $force -eq 0 ]; then
-		exit 1
-	    fi
-	fi
-	#echo curl -m2 -s -X DELETE http://${HSPROV}/private/${private_id}
-	privid_sta=$(curl -m2 -s -X DELETE http://${HSPROV}/private/${private_id})
-	#echo "privid_sta=${privid_sta}"
-	if [ ! -z "$privid_sta" ]; then
-	    if [[ $force == 0 || ( $force != 0 && $quiet == 0 ) ]]; then
-		printf "Error: couldn't delete private ID '%s'!\n" "${rprivate_id}"
-	    fi
-	    if [ $force -eq 0 ]; then
-		exit 1
+	    #echo curl -m2 -s -X DELETE http://${HSPROV}/irs/${irs_uuid}
+		irs_sta=$(curl -m2 -s -X DELETE http://${HSPROV}/irs/${irs_uuid})
+	    #echo "irs_sta=${irs_sta}"
+		if [ ! -z "$irs_sta" ]; then
+		    if [[ $force == 0 || ( $force != 0 && $quiet == 0 ) ]]; then
+			printf "Error: couldn't delete IRS!\n"
+		    fi
+		    if [ $force -eq 0 ]; then
+			exit 1
+		    fi
+		fi
+	    #echo curl -m2 -s -X DELETE http://${HSPROV}/private/${private_id}
+		privid_sta=$(curl -m2 -s -X DELETE http://${HSPROV}/private/${private_id})
+	    #echo "privid_sta=${privid_sta}"
+		if [ ! -z "$privid_sta" ]; then
+		    if [[ $force == 0 || ( $force != 0 && $quiet == 0 ) ]]; then
+			printf "Error: couldn't delete private ID '%s'!\n" "${rprivate_id}"
+		    fi
+		    if [ $force -eq 0 ]; then
+			exit 1
+		    fi
+		fi
 	    fi
 	fi
     done
diff --git a/homestead.root/usr/share/clearwater/bin/display_user b/homestead.root/usr/share/clearwater/bin/display_user
--- a/homestead.root/usr/share/clearwater/bin/display_user
+++ b/homestead.root/usr/share/clearwater/bin/display_user
@@ -49,6 +49,7 @@ Usage: $cmdname [OPTION...] <directory-number>[..<directory-number>] <domain>\n\
 \n\
 Options:\n\
   --hsprov IP:PORT  IP address and port of homestead-prov\n\
+  --hs IP:PORT      IP address and port of homestead\n\
   -k, --keep-going  keep going on errors\n\
   -q, --quiet       suppress errors when ignoring them\n\
   -s, --short       less verbose display\n\
@@ -67,7 +68,7 @@ error()
     usage
 }
 
-params="$(getopt -o hskq -l help,short,keep-going,quiet,hsprov: --name $cmdname -- "$@")"
+params="$(getopt -o hskq -l help,short,keep-going,quiet,hsprov:,hs: --name $cmdname -- "$@")"
 
 if [ $? -ne 0 ]
 then
@@ -86,6 +87,10 @@ do
 	;;
 	--hsprov)
 	export "HSPROV=${2-}"
+	shift 2
+	;;
+	--hs)
+	export "HS=${2-}"
 	shift 2
 	;;
 	-s|--short)
@@ -156,7 +161,14 @@ fi
 shift
 
 HSPROV=${LOCAL_IP}:${HTTP_PORT}
-HS=${LOCAL_IP}:8888
+if [ -z $HS ]; then
+    HS=${LOCAL_IP}
+fi
+HS_IP=( $(echo $HS|sed -e 's#:# #') )
+HS=${HS_IP[0]}:8888
+if [ ! -z "${HS_IP[1]}" ]; then
+    HS=${HS_IP[0]}:${HS_IP[1]}
+fi
 _USERS=(${USER//,/ })
 USERS=()
 SIZES=()
@@ -227,9 +239,23 @@ while [ $i -lt ${#USERS[@]} ]; do
 	    exit 1
 	fi
 
-	impu=$(curl -m5 -s http://${HSPROV}/impu/${public_id} 2>&1)
-	if [[ ${impu:0:1} == "<" ]]; then
-	    if [[ "$(curl -m5 -s http://${HSPROV}/impi/${private_id}/digest)" =~ digest_ha1 ]]; then
+	(
+	    curl -w "\nhttp_code=%{http_code}\n" -s -X GET http://${HSPROV}/private/${private_id}; echo $? > /tmp/hsprov.sta
+	) > /tmp/hsprov.out 2>&1
+	sta=$(cat /tmp/hsprov.sta)
+	if [ $sta -eq 0 ]; then
+	    eval "$(grep "^http_code=" /tmp/hsprov.out)"
+	    if [ $http_code -ne 200 ]; then
+		if [[ $keep_going == 0 || ( $keep_going != 0 && $quiet == 0 ) ]]; then
+		    printf "Error: user ${public_id} does not exist!\n"
+		fi
+		if [ $keep_going -eq 0 ]; then
+		    exit 1
+		fi
+	    else
+		digest=$(grep -v "^http_code=" /tmp/hsprov.out | python -c 'import json,sys;obj=json.load(sys.stdin);print obj["digest_ha1"]')
+		impu=$(curl -m5 -s http://${HSPROV}/impu/${public_id} 2>&1)
+
 		public_id=${public_id}
 
 		service_profile=$(curl -m5 -s -D - http://${HSPROV}/public/${public_id}/service_profile)
@@ -240,47 +266,32 @@ while [ $i -lt ${#USERS[@]} ]; do
 		    if [ $keep_going -eq 0 ]; then
 			exit 1
 		    fi
-		fi
-		service_profile=$(printf "%s" "${service_profile}"|grep "Location:"|awk '{print $2}'|tr '[[:space:]]' ' '|sed -e 's#[[:space:]]##g')
-		iFC=$(curl -m5 -s http://${HSPROV}${service_profile}/filter_criteria)
-
-		digest=$(curl -m5 -s http://${HSPROV}/impi/${private_id}/digest|python -c 'import json,sys;obj=json.load(sys.stdin);print obj["digest_ha1"]' 2>&1)
-
-		registered=$(curl -s "http://${HS}/impu/${public_id}/reg-data?private_id=${private_id}"|grep RegistrationState|sed -e 's#.*<RegistrationState[>]\([^<]*\).*#\1#')
-
-		if [ $short -eq 0 ]; then
-		    echo ${rprivate_id}:
-		    echo "  Registration state:"
-		    echo "    $registered"
-		    echo "  HA1 digest:"
-		    echo "    $digest"
-		    echo "  iFC:"
-		    (
-			if [ -z "$iFC" ]; then
-			    printf "Error: no iFC for user ${private_id}\n"
-			else
-			    echo ${iFC}|python -c 'import xml.dom.minidom, sys; print xml.dom.minidom.parse(sys.stdin).toprettyxml()'|sed -e '/^[[:space:]]*$/d'
-			fi
-		    ) 2>&1 | while IFS='' read -r line; do
-			printf "     %s\n" "$line"
-		    done
 		else
-		    printf "%s:%s\n" "${rprivate_id}" "${digest}"
+		    service_profile=$(printf "%s" "${service_profile}"|grep "Location:"|awk '{print $2}'|tr '[[:space:]]' ' '|sed -e 's#[[:space:]]##g')
+		    iFC=$(curl -m5 -s http://${HSPROV}${service_profile}/filter_criteria)
+
+		    registered=$(curl -s "http://${HS}/impu/${public_id}/reg-data?private_id=${private_id}"|grep RegistrationState|sed -e 's#.*<RegistrationState[>]\([^<]*\).*#\1#')
+
+		    if [ $short -eq 0 ]; then
+			echo ${rprivate_id}:
+			echo "  Registration state:"
+			echo "    $registered"
+			echo "  HA1 digest:"
+			echo "    $digest"
+			echo "  iFC:"
+			(
+			    if [ -z "$iFC" ]; then
+				printf "Error: no iFC for user ${private_id}\n"
+			    else
+				echo ${iFC}|python -c 'import xml.dom.minidom, sys; print xml.dom.minidom.parse(sys.stdin).toprettyxml()'|sed -e '/^[[:space:]]*$/d'
+			    fi
+			) 2>&1 | while IFS='' read -r line; do
+			    printf "     %s\n" "$line"
+			done
+		    else
+			printf "%s:%s\n" "${rprivate_id}" "${digest}"
+		    fi
 		fi
-	    else
-		if [[ $keep_going == 0 || ( $keep_going != 0 && $quiet == 0 ) ]]; then
-		    printf "Error: no IMPI user ${private_id}\n"
-		fi
-		if [ $keep_going -eq 0 ]; then
-		    exit 1
-		fi
-	    fi
-	else
-	    if [[ $keep_going == 0 || ( $keep_going != 0 && $quiet == 0 ) ]]; then
-		printf "Error: no IMPU user '%s'\n" "${rpublic_id}"
-	    fi
-	    if [ $keep_going -eq 0 ]; then
-		exit 1
 	    fi
 	fi
     done
diff --git a/homestead.root/usr/share/clearwater/bin/update_user b/homestead.root/usr/share/clearwater/bin/update_user
--- a/homestead.root/usr/share/clearwater/bin/update_user
+++ b/homestead.root/usr/share/clearwater/bin/update_user
@@ -47,6 +47,7 @@ Usage: $cmdname [OPTION...] <directory-number>[...<directory-number>] <domain> <
 \n\
 Options:\n\
   --hsprov IP:PORT  IP address and port of homestead-prov\n\
+  --hs IP:PORT      IP address and port of homestead\n\
   -q, --quiet       don't display the user\n\
   -h, --help        display this usage\n"
 
@@ -63,7 +64,7 @@ error()
     usage
 }
 
-params="$(getopt -o hq -l help,quiet,hsprov: --name $cmdname -- "$@")"
+params="$(getopt -o hq -l help,quiet,hsprov:,hs: --name $cmdname -- "$@")"
 
 if [ $? -ne 0 ]
 then
@@ -82,6 +83,10 @@ do
 	;;
 	--hsprov)
 	export "HSPROV=${2-}"
+	shift 2
+	;;
+	--hs)
+	export "HS=${2-}"
 	shift 2
 	;;
         -q|--quiet)
@@ -149,6 +154,15 @@ fi
 shift
 
 HSPROV=${LOCAL_IP}:${HTTP_PORT}
+if [ -z $HS ]; then
+    HS=${LOCAL_IP}
+fi
+HS_IP=( $(echo $HS|sed -e 's#:# #') )
+HS=${HS_IP[0]}:8888
+if [ ! -z "${HS_IP[1]}" ]; then
+    HS=${HS_IP[0]}:${HS_IP[1]}
+fi
+
 _USERS=(${USER//,/ })
 USERS=()
 SIZES=()
@@ -217,17 +231,26 @@ while [ $i -lt ${#USERS[@]} ]; do
 	    exit 1
 	fi
 
-	impu=$(curl -s http://${HSPROV}/impu/${public_id} 2>&1)
-	if [[ ${impu:0:1} == "<" ]]; then
-	    if [[ "$(curl -s http://${HSPROV}/impi/${private_id}/digest)" =~ digest_ha1 ]]; then
-		public_id=${public_id}
+	(
+	    curl -w "\nhttp_code=%{http_code}\n" -s -X GET http://${HSPROV}/private/${private_id}; echo $? > /tmp/hsprov.sta
+	) > /tmp/hsprov.out 2>&1
+	sta=$(cat /tmp/hsprov.sta)
+	if [ $sta -eq 0 ]; then
+	    eval "$(grep "^http_code=" /tmp/hsprov.out)"
+	    if [ $http_code -ne 200 ]; then
+		if [[ $force == 0 || ( $force != 0 && $quiet == 0 ) ]]; then
+		    printf "Error: user ${public_id} does not exist!\n"
+		    exit 1
+		fi
+	    else
+		digest=$(grep -v "^http_code=" /tmp/hsprov.out | python -c 'import json,sys;obj=json.load(sys.stdin);print obj["digest_ha1"]')
 
 		service_profile=$(
 		    curl -s -D - http://${HSPROV}/public/${public_id}/service_profile|\
-                grep "Location:"|\
-                awk '{print $2}'|\
-                tr '[[:space:]]' ' '|\
-                sed -e 's#[[:space:]]##g'
+                    grep "Location:"|\
+                    awk '{print $2}'|\
+                    tr '[[:space:]]' ' '|\
+                    sed -e 's#[[:space:]]##g'
 		)
 
 		new_digest=$(
@@ -236,7 +259,7 @@ while [ $i -lt ${#USERS[@]} ]; do
 		json_digest="{\"digest_ha1\": \"${new_digest}\", \"realm\": \"${DOMAIN}\"}"
 		put_sta=$(
 		    printf "%s\n" "${json_digest}"|\
-                curl -s curl -X PUT -d @- http://${HSPROV}/private/${private_id}
+                    curl -s curl -X PUT -d @- http://${HSPROV}/private/${private_id}
 		)
 		if [ ! -z $put_sta ]; then
 		    printf "Error: couldn't update password!\n"
@@ -246,12 +269,9 @@ while [ $i -lt ${#USERS[@]} ]; do
 		if [ $quiet -eq 0 ];then
 		    ${mydir}/display_user ${rUSER} ${DOMAIN}
 		fi
-            else
-		printf "Error: no IMPI user ${private_id}\n"
-		exit 1
 	    fi
 	else
-            printf "Error: no IMPU user '${public_id}'\n"
+            printf "Error: user '${public_id}' does not exist!\n"
 	    exit 1
 	fi
     done
