More updates

diff --git a/homestead.root/usr/share/clearwater/bin/create_user b/homestead.root/usr/share/clearwater/bin/create_user
--- a/homestead.root/usr/share/clearwater/bin/create_user
+++ b/homestead.root/usr/share/clearwater/bin/create_user
@@ -2,6 +2,7 @@
 
 mydir=$(cd `dirname $0`;pwd)
 cwd=$(pwd)
+quiet=0
 
 cmdname=$0
 export "PREFIX=123"
@@ -9,11 +10,12 @@ export "PREFIX=123"
 usage()
 {
     printf "\
-Usage: $cmdname [OPTION...] <directory-number> <domain> <password>\n\
+Usage: $cmdname [OPTION...] <directory-number>[...<directory-number>] <domain> <password>\n\
 \n\
 Options:\n\
   --prefix PREFIX   twin-prefix (default: 123)\n\
   --ifc iFC-FILE    XML file containing the iFC\n\
+  -q, --quiet       don't display the user\n\
   -h, --help        display this usage\n"
 
     printf "\n"
@@ -29,7 +31,7 @@ error()
     usage
 }
 
-params="$(getopt -o h -l help,prefix:,ifc: --name $cmdname -- "$@")"
+params="$(getopt -o hq -l help,prefix:,ifc:,quiet --name $cmdname -- "$@")"
 
 if [ $? -ne 0 ]
 then
@@ -54,6 +56,10 @@ do
 	shift
 	break
 	;;
+        -q|--quiet)
+        let "quiet=1"
+	shift
+        ;;
         -h|--help)
         usage
         ;;
@@ -133,103 +139,126 @@ print xml.dom.minidom.parse(sys.stdin).toprettyxml()\
 fi
 
 HSPROV=${LOCAL_IP}:${HTTP_PORT}
-public_id=sip:${USER}@${DOMAIN}
-private_id=${USER}@${DOMAIN}
+_USERS=(${USER//,/ })
+USERS=()
+for _USER in ${_USERS[@]}; do
+    seq_USERS=(${_USER//./ })
+    if [ ${#seq_USERS[@]} -eq 1 ]; then
+        seq_USERS[1]=${seq_USERS[0]}
+    fi
+    if [[ "${seq_USERS[0]}" =~ [^0-9] ]]; then
+	printf "Error: invalid user range - ${seq_USERS[0]}..${seq_USERS[1]}!\n"
+	exit 1
+    fi
+    if [[ "${seq_USERS[1]}" =~ [^0-9] ]]; then
+	printf "Error: invalid user range - ${seq_USERS[0]}..${seq_USERS[1]}!\n"
+	exit 1
+    fi
+    if [ ${seq_USERS[0]} -gt ${seq_USERS[1]} ]; then
+	printf "Error: invalid user range - ${seq_USERS[0]}..${seq_USERS[1]}!\n"
+	exit 1
+    fi
+    USERS[${#USERS[@]}]="{${seq_USERS[0]}..${seq_USERS[1]}}"
+done
 
-if [ "$(curl -s http://${HSPROV}/ping 2>&1)" != "OK" ]; then
-    printf "Error: can't contact homestead-prov @ http://${HSPROV}!\n"
-    exit 1
-fi
+for USER in $(eval echo ${USERS[@]}); do
+    public_id=sip:${USER}@${DOMAIN}
+    private_id=${USER}@${DOMAIN}
 
-impu=$(curl -s http://${HSPROV}/impu/${public_id} 2>&1)
-if [[ ${impu:0:1} == "<" ]]; then
-    printf "Error: IMPU user '${public_id}' already exists!\n"
-    exit 1
-fi
-  
-if [[ "$(curl -s http://${HSPROV}/impi/${private_id}/digest)" =~ digest_ha1 ]]; then
-    printf "Error: IMPI user '${private_id}' already exists!\n"
-    exit 1
-fi
+    if [ "$(curl -s http://${HSPROV}/ping 2>&1)" != "OK" ]; then
+	printf "Error: can't contact homestead-prov @ http://${HSPROV}!\n"
+	exit 1
+    fi
 
-#
-# Create the private ID
-#
-new_digest=$(
-    printf "${private_id}:${DOMAIN}:${PASSWORD}"|md5sum|awk '{print $1}'
-)
-json_digest="{\"digest_ha1\": \"${new_digest}\", \"realm\": \"${DOMAIN}\"}"
-#echo "json_digest=${json_digest}"
-put_sta=$(
-    printf "%s\n" "${json_digest}" |\
+    impu=$(curl -s http://${HSPROV}/impu/${public_id} 2>&1)
+    if [[ ${impu:0:1} == "<" ]]; then
+	printf "Error: IMPU user '${public_id}' already exists!\n"
+	exit 1
+    fi
+    
+    if [[ "$(curl -s http://${HSPROV}/impi/${private_id}/digest)" =~ digest_ha1 ]]; then
+	printf "Error: IMPI user '${private_id}' already exists!\n"
+	exit 1
+    fi
+
+    #
+    # Create the private ID
+    #
+    new_digest=$(
+	printf "${private_id}:${DOMAIN}:${PASSWORD}"|md5sum|awk '{print $1}'
+    )
+    json_digest="{\"digest_ha1\": \"${new_digest}\", \"realm\": \"${DOMAIN}\"}"
+    #echo "json_digest=${json_digest}"
+    put_sta=$(
+	printf "%s\n" "${json_digest}" |\
     curl -s -X PUT -d @- http://${HSPROV}/private/${private_id}
-)
-if [ ! -z "$put_sta" ]; then
-    printf "Error: couldn't create IMPU user '${public_id}'!\n"
-    exit 1
-fi
+    )
+    if [ ! -z "$put_sta" ]; then
+	printf "Error: couldn't create IMPU user '${public_id}'!\n"
+	exit 1
+    fi
 
-#
-# Create IRS
-#
-irs_uuid=$(
-    curl -s -D - -X POST http://${HSPROV}/irs|\
+    #
+    # Create IRS
+    #
+    irs_uuid=$(
+	curl -s -D - -X POST http://${HSPROV}/irs|\
     grep "Location:"|awk '{print $2}'|\
     sed -e 's#[[:space:]]##g'|\
     sed -e 's#/irs/##'
-)
-#echo "irs_uuid=$irs_uuid"
+    )
+    #echo "irs_uuid=$irs_uuid"
 
-#
-# Associate the private ID with the new IRS
-#
-#echo curl -s -X PUT http://${HSPROV}/private/${private_id}/associated_implicit_registration_sets/${irs_uuid}
-rsp=$(
-    curl -s -X PUT http://${HSPROV}/private/${private_id}/associated_implicit_registration_sets/${irs_uuid}
-)
-if [ ! -z $rsp ]; then
-    printf "Error: couldn't associate '${private_id}' with IRS '${irs_uuid}!\n"
-    ${mydir}/delete_user -fq ${USER} ${DOMAIN}
-    exit 1
-fi
+    #
+    # Associate the private ID with the new IRS
+    #
+    #echo curl -s -X PUT http://${HSPROV}/private/${private_id}/associated_implicit_registration_sets/${irs_uuid}
+    rsp=$(
+	curl -s -X PUT http://${HSPROV}/private/${private_id}/associated_implicit_registration_sets/${irs_uuid}
+    )
+    if [ ! -z $rsp ]; then
+	printf "Error: couldn't associate '${private_id}' with IRS '${irs_uuid}!\n"
+	${mydir}/delete_user -fq ${USER} ${DOMAIN}
+	exit 1
+    fi
 
-#
-# Create the service profile
-#
-#echo curl -s -X POST http://${HSPROV}/irs/${irs_uuid}/service_profiles
-sp_uuid=$(
-    curl -s -D - -X POST http://${HSPROV}/irs/${irs_uuid}/service_profiles|\
+    #
+    # Create the service profile
+    #
+    #echo curl -s -X POST http://${HSPROV}/irs/${irs_uuid}/service_profiles
+    sp_uuid=$(
+	curl -s -D - -X POST http://${HSPROV}/irs/${irs_uuid}/service_profiles|\
     grep "Location:"|\
     awk '{print $2}'|\
     sed -e 's#[[:space:]]##g'|\
     sed -e 's#/irs/.*/service_profiles/##'
-)
-#echo "sp_uuid=$sp_uuid"
+    )
+    #echo "sp_uuid=$sp_uuid"
 
-#
-# Create public ID
-#
-pubid_sta=$(
-    printf "<PublicIdentity><Identity>%s</Identity></PublicIdentity>\n" "${public_id}"|\
+    #
+    # Create public ID
+    #
+    pubid_sta=$(
+	printf "<PublicIdentity><Identity>%s</Identity></PublicIdentity>\n" "${public_id}"|\
     curl -s -X PUT -d @- http://${HSPROV}/irs/${irs_uuid}/service_profiles/${sp_uuid}/public_ids/${public_id}
-)
-if [ ! -z $pubid_sta ]; then
-    printf "Error: couldn't create public ID '${public_id}'!\n"
-    ${mydir}/delete_user -fq ${USER} ${DOMAIN}
-    exit 1
-fi
+    )
+    if [ ! -z $pubid_sta ]; then
+	printf "Error: couldn't create public ID '${public_id}'!\n"
+	${mydir}/delete_user -fq ${USER} ${DOMAIN}
+	exit 1
+    fi
 
-#
-# Set iFC
-#
-service_profile=$(
-    curl -s -D - http://${HSPROV}/public/${public_id}/service_profile|\
+    #
+    # Set iFC
+    #
+    service_profile=$(
+	curl -s -D - http://${HSPROV}/public/${public_id}/service_profile|\
     grep "Location:"|\
     awk '{print $2}'|\
     tr '[[:space:]]' ' '|sed -e 's#[[:space:]]##g'
-)
-if [ -z $IFC ]; then
-    cat > $$.iFC <<'EOF'
+    )
+    if [ -z $IFC ]; then
+	    cat > $$.iFC <<'EOF'
 <?xml version="1.0" ?>
 <ServiceProfile>
   <InitialFilterCriteria>
@@ -268,23 +297,26 @@ if [ -z $IFC ]; then
   </InitialFilterCriteria>
 </ServiceProfile>
 EOF
-else
-    cat $IFC > $$.iFC
-fi
+    else
+	cat $IFC > $$.iFC
+    fi
 
-sed -ie "s#\${DOMAIN}#${DOMAIN}#g" $$.iFC
-sed -ie "s#\${PREFIX}#${PREFIX}#g" $$.iFC
-
-ifc_sta=$(
-    cat $$.iFC|\
+    sed -ie "s#\${DOMAIN}#${DOMAIN}#g" $$.iFC
+    sed -ie "s#\${PREFIX}#${PREFIX}#g" $$.iFC
+    
+    ifc_sta=$(
+	cat $$.iFC|\
     curl -s -X PUT -d @- http://${HSPROV}${service_profile}/filter_criteria
-)
-if [ ! -z $ifc_sta ]; then
-    printf "Error: couldn't update iFC!\n"
-    ${mydir}/delete_user -fq ${USER} ${DOMAIN}
-    exit 1
-fi
+    )
+    if [ ! -z $ifc_sta ]; then
+	printf "Error: couldn't update iFC!\n"
+	${mydir}/delete_user -fq ${USER} ${DOMAIN}
+	exit 1
+    fi
 
-rm -f $$.iFC*
+    rm -f $$.iFC*
 
-${mydir}/display_user ${USER} ${DOMAIN}
+    if [ $quiet -eq 0 ];then
+	${mydir}/display_user ${USER} ${DOMAIN}
+    fi    
+done
diff --git a/homestead.root/usr/share/clearwater/bin/delete_user b/homestead.root/usr/share/clearwater/bin/delete_user
--- a/homestead.root/usr/share/clearwater/bin/delete_user
+++ b/homestead.root/usr/share/clearwater/bin/delete_user
@@ -10,7 +10,7 @@ cmdname=$0
 usage()
 {
     printf "\
-Usage: $cmdname [OPTION...] <directory-number> <domain>\n\
+Usage: $cmdname [OPTION...] <directory-number>[..<directory-number>] <domain>\n\
 \n\
 Options:\n\
   -f, --force       proceed with delete in the face of errors\n\
@@ -112,88 +112,110 @@ fi
 shift
 
 HSPROV=${LOCAL_IP}:${HTTP_PORT}
-public_id=sip:${USER}@${DOMAIN}
-private_id=${USER}@${DOMAIN}
-
-if [ "$(curl -s http://${HSPROV}/ping 2>&1)" != "OK" ]; then
-    printf "Error: can't contact homestead-prov @ http://${HSPROV}!\n"
-    exit 1
-fi
-
-impu=$(curl -s http://${HSPROV}/impu/${public_id} 2>&1)
-if [[ ${impu:0:1} != "<" ]]; then
-    if [[ $force == 0 || ( $force != 0 && $quiet == 0 ) ]]; then
-	printf "Error: IMPU user '${public_id}' does not exist!\n"
+_USERS=(${USER//,/ })
+USERS=()
+for _USER in ${_USERS[@]}; do
+    seq_USERS=(${_USER//./ })
+    if [ ${#seq_USERS[@]} -eq 1 ]; then
+        seq_USERS[1]=${seq_USERS[0]}
     fi
-    if [ $force -eq 0 ]; then
+    if [[ "${seq_USERS[0]}" =~ [^0-9] ]]; then
+	printf "Error: invalid user range - ${seq_USERS[0]}..${seq_USERS[1]}!\n"
 	exit 1
     fi
-fi
-  
-if [[ ! "$(curl -s http://${HSPROV}/impi/${private_id}/digest)" =~ digest_ha1 ]]; then
-    if [[ $force == 0 || ( $force != 0 && $quiet == 0 ) ]]; then
-	printf "Error: IMPI user '${private_id}' does not exist!\n"
-    fi
-    if [ $force -eq 0 ]; then
+    if [[ "${seq_USERS[1]}" =~ [^0-9] ]]; then
+	printf "Error: invalid user range - ${seq_USERS[0]}..${seq_USERS[1]}!\n"
 	exit 1
     fi
-fi
+    if [ ${seq_USERS[0]} -gt ${seq_USERS[1]} ]; then
+	printf "Error: invalid user range - ${seq_USERS[0]}..${seq_USERS[1]}!\n"
+	exit 1
+    fi
+    USERS[${#USERS[@]}]="{${seq_USERS[0]}..${seq_USERS[1]}}"
+done
 
-sp_url=$(
-    curl -s -D - http://${HSPROV}/public/${public_id}/service_profile|\
+for USER in $(eval echo ${USERS[@]}); do
+    public_id=sip:${USER}@${DOMAIN}
+    private_id=${USER}@${DOMAIN}
+
+    if [ "$(curl -s http://${HSPROV}/ping 2>&1)" != "OK" ]; then
+	printf "Error: can't contact homestead-prov @ http://${HSPROV}!\n"
+	exit 1
+    fi
+
+    impu=$(curl -s http://${HSPROV}/impu/${public_id} 2>&1)
+    if [[ ${impu:0:1} != "<" ]]; then
+	if [[ $force == 0 || ( $force != 0 && $quiet == 0 ) ]]; then
+	    printf "Error: IMPU user '${public_id}' does not exist!\n"
+	fi
+	if [ $force -eq 0 ]; then
+	    exit 1
+	fi
+    fi
+    
+    if [[ ! "$(curl -s http://${HSPROV}/impi/${private_id}/digest)" =~ digest_ha1 ]]; then
+	if [[ $force == 0 || ( $force != 0 && $quiet == 0 ) ]]; then
+	    printf "Error: IMPI user '${private_id}' does not exist!\n"
+	fi
+	if [ $force -eq 0 ]; then
+	    exit 1
+	fi
+    fi
+
+    sp_url=$(
+	curl -s -D - http://${HSPROV}/public/${public_id}/service_profile|\
         grep "Location:"|\
         awk '{print $2}'|\
         sed -e 's#[[:space:]]##g'
-)
-#echo "sp_url=${sp_url}"
-sp_uuid=$(echo ${sp_url}|sed -e 's#/irs/.*/service_profiles/##')
-#echo "sp_uuid=${sp_uuid}"
-irs_uuid=$(
-    curl -s http://${HSPROV}/private/${private_id}/associated_implicit_registration_sets|\
+    )
+    #echo "sp_url=${sp_url}"
+    sp_uuid=$(echo ${sp_url}|sed -e 's#/irs/.*/service_profiles/##')
+    #echo "sp_uuid=${sp_uuid}"
+    irs_uuid=$(
+	curl -s http://${HSPROV}/private/${private_id}/associated_implicit_registration_sets|\
         python -c 'import json,sys;obj=json.load(sys.stdin);print obj["associated_implicit_registration_sets"][0]' 2>&1
-)
-#echo "irs_uuid=${irs_uuid}"
+    )
+    #echo "irs_uuid=${irs_uuid}"
 
-#
-# Delete the public ID
-#
-pubid_sta=$(
-    curl -s -X DELETE http://${HSPROV}${sp_url}/public_ids/${public_id}
-)
+    #
+    # Delete the public ID
+    #
+    pubid_sta=$(
+	curl -s -X DELETE http://${HSPROV}${sp_url}/public_ids/${public_id}
+    )
     #echo "pubid_sta=${pubid_sta}"
-if [ ! -z "$pubid_sta" ]; then
-    if [[ $force == 0 || ( $force != 0 && $quiet == 0 ) ]]; then
-	printf "Error: couldn't delete public ID '${public_id}'!\n"
+    if [ ! -z "$pubid_sta" ]; then
+	if [[ $force == 0 || ( $force != 0 && $quiet == 0 ) ]]; then
+	    printf "Error: couldn't delete public ID '${public_id}'!\n"
+	fi
+	if [ $force -eq 0 ]; then
+	    exit 1
+	fi
     fi
-    if [ $force -eq 0 ]; then
-	exit 1
-    fi
-fi
 
-#
-# Delete public ID
-#
-#echo curl -s -X DELETE http://${HSPROV}/irs/${irs_uuid}
-irs_sta=$(curl -s -X DELETE http://${HSPROV}/irs/${irs_uuid})
-#echo "irs_sta=${irs_sta}"
-if [ ! -z "$irs_sta" ]; then
-    if [[ $force == 0 || ( $force != 0 && $quiet == 0 ) ]]; then
-	printf "Error: couldn't delete IRS!\n"
+    #
+    # Delete public ID
+    #
+    #echo curl -s -X DELETE http://${HSPROV}/irs/${irs_uuid}
+    irs_sta=$(curl -s -X DELETE http://${HSPROV}/irs/${irs_uuid})
+    #echo "irs_sta=${irs_sta}"
+    if [ ! -z "$irs_sta" ]; then
+	if [[ $force == 0 || ( $force != 0 && $quiet == 0 ) ]]; then
+	    printf "Error: couldn't delete IRS!\n"
+	fi
+	if [ $force -eq 0 ]; then
+	    exit 1
+	fi
     fi
-    if [ $force -eq 0 ]; then
-	exit 1
+    #echo curl -m5 -s -X DELETE http://${HSPROV}/private/${private_id}
+    privid_sta=$(curl -m5 -s -X DELETE http://${HSPROV}/private/${private_id})
+    #echo "privid_sta=${privid_sta}"
+    if [ ! -z "$privid_sta" ]; then
+	if [[ $force == 0 || ( $force != 0 && $quiet == 0 ) ]]; then
+	    printf "Error: couldn't delete private ID '${private_id}'!\n"
+	fi
+	if [ $force -eq 0 ]; then
+	    exit 1
+	fi
     fi
-fi
-#echo curl -m5 -s -X DELETE http://${HSPROV}/private/${private_id}
-privid_sta=$(curl -m5 -s -X DELETE http://${HSPROV}/private/${private_id})
-#echo "privid_sta=${privid_sta}"
-if [ ! -z "$privid_sta" ]; then
-    if [[ $force == 0 || ( $force != 0 && $quiet == 0 ) ]]; then
-	printf "Error: couldn't delete private ID '${private_id}'!\n"
-    fi
-    if [ $force -eq 0 ]; then
-	exit 1
-    fi
-fi
-
-
+done
diff --git a/homestead.root/usr/share/clearwater/bin/display_user b/homestead.root/usr/share/clearwater/bin/display_user
--- a/homestead.root/usr/share/clearwater/bin/display_user
+++ b/homestead.root/usr/share/clearwater/bin/display_user
@@ -2,15 +2,21 @@
 
 mydir=$(cd `dirname $0`;pwd)
 cwd=$(pwd)
+short=0
+keep_going=0
+quiet=0
 
 cmdname=$0
 
 usage()
 {
     printf "\
-Usage: $cmdname [OPTION...] <directory-number> <domain>\n\
+Usage: $cmdname [OPTION...] <directory-number>[..<directory-number>] <domain>\n\
 \n\
 Options:\n\
+  -k, --keep-going  keep going on errors\n\
+  -q, --quiet       suppress errors when ignoring them\n\
+  -s, --short       less verbose display\n\
   -h, --help        display this usage\n"
 
     printf "\n"
@@ -26,7 +32,7 @@ error()
     usage
 }
 
-params="$(getopt -o h -l help --name $cmdname -- "$@")"
+params="$(getopt -o hskq -l help,short,keep-going,quiet --name $cmdname -- "$@")"
 
 if [ $? -ne 0 ]
 then
@@ -42,6 +48,18 @@ do
 	--)
 	shift
 	break
+	;;
+	-s|--short)
+	let "short=1"
+	shift
+	;;
+	-q|--quiet)
+	let "quiet=1"
+	shift
+	;;
+	-k|--keep-going)
+	let "keep_going=1"
+	shift
 	;;
         -h|--help)
         usage
@@ -92,38 +110,87 @@ fi
 shift
 
 HSPROV=${LOCAL_IP}:${HTTP_PORT}
-public_id=sip:${USER}@${DOMAIN}
-private_id=${USER}@${DOMAIN}
-
-if [ "$(curl -s http://${HSPROV}/ping 2>&1)" != "OK" ]; then
-    printf "Error: can't contact homestead-prov @ http://${HSPROV}!\n"
-    exit 1
-fi
-
-impu=$(curl -s http://${HSPROV}/impu/${public_id} 2>&1)
-if [[ ${impu:0:1} == "<" ]]; then
-    if [[ "$(curl -s http://${HSPROV}/impi/${private_id}/digest)" =~ digest_ha1 ]]; then
-	public_id=${public_id}
-
-	service_profile=$(curl -s -D - http://${HSPROV}/public/${public_id}/service_profile|grep "Location:"|awk '{print $2}'|tr '[[:space:]]' ' '|sed -e 's#[[:space:]]##g')
-	iFC=$(curl -s http://${HSPROV}${service_profile}/filter_criteria)
-
-	digest=$(curl -s http://${HSPROV}/impi/${private_id}/digest|python -c 'import json,sys;obj=json.load(sys.stdin);print obj["digest_ha1"]' 2>&1)
-
-	echo "HA1 digest:"
-        echo "  $digest"
-	echo "iFC:"
-	(
-	    echo ${iFC}|python -c 'import xml.dom.minidom, sys; print xml.dom.minidom.parse(sys.stdin).toprettyxml()'|sed -e '/^[[:space:]]*$/d'
-	) 2>&1 | while IFS='' read -r line; do
-	    printf "   %s\n" "$line"
-	done
-    else
-	printf "Error: no IMPI user ${private_id}\n"
+_USERS=(${USER//,/ })
+USERS=()
+for _USER in ${_USERS[@]}; do
+    seq_USERS=(${_USER//./ })
+    if [ ${#seq_USERS[@]} -eq 1 ]; then
+        seq_USERS[1]=${seq_USERS[0]}
+    fi
+    if [[ "${seq_USERS[0]}" =~ [^0-9] ]]; then
+	printf "Error: invalid user range - ${seq_USERS[0]}..${seq_USERS[1]}!\n"
 	exit 1
     fi
-else
-    printf "Error: no IMPU user '${public_id}'\n"
-    exit 1
-fi
+    if [[ "${seq_USERS[1]}" =~ [^0-9] ]]; then
+	printf "Error: invalid user range - ${seq_USERS[0]}..${seq_USERS[1]}!\n"
+	exit 1
+    fi
+    if [ ${seq_USERS[0]} -gt ${seq_USERS[1]} ]; then
+	printf "Error: invalid user range - ${seq_USERS[0]}..${seq_USERS[1]}!\n"
+	exit 1
+    fi
+    USERS[${#USERS[@]}]="{${seq_USERS[0]}..${seq_USERS[1]}}"
+done
 
+for USER in $(eval echo ${USERS[@]}); do
+    public_id=sip:${USER}@${DOMAIN}
+    private_id=${USER}@${DOMAIN}
+
+    if [ "$(curl -m5 -s http://${HSPROV}/ping 2>&1)" != "OK" ]; then
+	printf "Error: can't contact homestead-prov @ http://${HSPROV}!\n"
+	exit 1
+    fi
+
+    impu=$(curl -m5 -s http://${HSPROV}/impu/${public_id} 2>&1)
+    if [[ ${impu:0:1} == "<" ]]; then
+	if [[ "$(curl -m5 -s http://${HSPROV}/impi/${private_id}/digest)" =~ digest_ha1 ]]; then
+	    public_id=${public_id}
+
+	    service_profile=$(curl -m5 -s -D - http://${HSPROV}/public/${public_id}/service_profile)
+	    if [ $? -ne 0 ]; then
+		if [[ $keep_going == 0 || ( $keep_going != 0 && $quiet == 0 ) ]]; then
+		    printf "Error: couldn't retrieve server profile for user ${private_id}\n"
+		fi
+		if [ $keep_going -eq 0 ]; then
+		    exit 1
+		fi
+	    fi
+	    service_profile=$(printf "%s" "${service_profile}"|grep "Location:"|awk '{print $2}'|tr '[[:space:]]' ' '|sed -e 's#[[:space:]]##g')
+	    iFC=$(curl -m5 -s http://${HSPROV}${service_profile}/filter_criteria)
+
+	    digest=$(curl -m5 -s http://${HSPROV}/impi/${private_id}/digest|python -c 'import json,sys;obj=json.load(sys.stdin);print obj["digest_ha1"]' 2>&1)
+
+	    if [ $short -eq 0 ]; then
+		echo ${private_id}:
+		echo "  HA1 digest:"
+		echo "    $digest"
+		echo "  iFC:"
+		(
+		    if [ -z "$iFC" ]; then
+			printf "Error: no iFC for user ${private_id}\n"
+		    else
+			echo ${iFC}|python -c 'import xml.dom.minidom, sys; print xml.dom.minidom.parse(sys.stdin).toprettyxml()'|sed -e '/^[[:space:]]*$/d'
+		    fi
+		) 2>&1 | while IFS='' read -r line; do
+		    printf "     %s\n" "$line"
+		done
+	    else
+		printf "%s:%s\n" "${private_id}" "${digest}"
+	    fi
+	else
+	    if [[ $keep_going == 0 || ( $keep_going != 0 && $quiet == 0 ) ]]; then
+		printf "Error: no IMPI user ${private_id}\n"
+	    fi
+	    if [ $keep_going -eq 0 ]; then
+		exit 1
+	    fi
+	fi
+    else
+	if [[ $keep_going == 0 || ( $keep_going != 0 && $quiet == 0 ) ]]; then
+	    printf "Error: no IMPU user '${public_id}'\n"
+	fi
+	if [ $keep_going -eq 0 ]; then
+	    exit 1
+	fi
+    fi
+done
diff --git a/homestead.root/usr/share/clearwater/bin/update_user b/homestead.root/usr/share/clearwater/bin/update_user
--- a/homestead.root/usr/share/clearwater/bin/update_user
+++ b/homestead.root/usr/share/clearwater/bin/update_user
@@ -2,15 +2,17 @@
 
 mydir=$(cd `dirname $0`;pwd)
 cwd=$(pwd)
+quiet=0
 
 cmdname=$0
 
 usage()
 {
     printf "\
-Usage: $cmdname [OPTION...] <directory-number> <domain> <password>\n\
+Usage: $cmdname [OPTION...] <directory-number>[...<directory-number>] <domain> <password>\n\
 \n\
 Options:\n\
+  -q, --quiet       don't display the user\n\
   -h, --help        display this usage\n"
 
     printf "\n"
@@ -26,7 +28,7 @@ error()
     usage
 }
 
-params="$(getopt -o h -l help --name $cmdname -- "$@")"
+params="$(getopt -o hq -l help,quiet --name $cmdname -- "$@")"
 
 if [ $? -ne 0 ]
 then
@@ -43,6 +45,10 @@ do
 	shift
 	break
 	;;
+        -q|--quiet)
+        let "quiet=1"
+	shift
+        ;;
         -h|--help)
         usage
         ;;
@@ -106,47 +112,72 @@ fi
 shift
 
 HSPROV=${LOCAL_IP}:${HTTP_PORT}
-public_id=sip:${USER}@${DOMAIN}
-private_id=${USER}@${DOMAIN}
-
-if [ "$(curl -s http://${HSPROV}/ping 2>&1)" != "OK" ]; then
-    printf "Error: can't contact homestead-prov @ http://${HSPROV}!\n"
-    exit 1
-fi
-
-impu=$(curl -s http://${HSPROV}/impu/${public_id} 2>&1)
-if [[ ${impu:0:1} == "<" ]]; then
-    if [[ "$(curl -s http://${HSPROV}/impi/${private_id}/digest)" =~ digest_ha1 ]]; then
-	public_id=${public_id}
-
-	service_profile=$(
-	    curl -s -D - http://${HSPROV}/public/${public_id}/service_profile|\
-            grep "Location:"|\
-            awk '{print $2}'|\
-            tr '[[:space:]]' ' '|\
-            sed -e 's#[[:space:]]##g'
-        )
-
-	new_digest=$(
-	    printf "${private_id}:${DOMAIN}:${PASSWORD}"|md5sum|awk '{print $1}'
-	)
-	json_digest="{\"digest_ha1\": \"${new_digest}\", \"realm\": \"${DOMAIN}\"}"
-	put_sta=$(
-	    printf "%s\n" "${json_digest}"|\
-            curl -s curl -X PUT -d @- http://${HSPROV}/private/${private_id}
-	)
-	if [ ! -z $put_sta ]; then
-	    printf "Error: couldn't update password!\n"
-	    exit 1
-	fi
-
-	${mydir}/display_user ${USER} ${DOMAIN}
-    else
-	printf "Error: no IMPI user ${private_id}\n"
+_USERS=(${USER//,/ })
+USERS=()
+for _USER in ${_USERS[@]}; do
+    seq_USERS=(${_USER//./ })
+    if [ ${#seq_USERS[@]} -eq 1 ]; then
+        seq_USERS[1]=${seq_USERS[0]}
+    fi
+    if [[ "${seq_USERS[0]}" =~ [^0-9] ]]; then
+	printf "Error: invalid user range - ${seq_USERS[0]}..${seq_USERS[1]}!\n"
 	exit 1
     fi
-else
-    printf "Error: no IMPU user '${public_id}'\n"
-    exit 1
-fi
+    if [[ "${seq_USERS[1]}" =~ [^0-9] ]]; then
+	printf "Error: invalid user range - ${seq_USERS[0]}..${seq_USERS[1]}!\n"
+	exit 1
+    fi
+    if [ ${seq_USERS[0]} -gt ${seq_USERS[1]} ]; then
+	printf "Error: invalid user range - ${seq_USERS[0]}..${seq_USERS[1]}!\n"
+	exit 1
+    fi
+    USERS[${#USERS[@]}]="{${seq_USERS[0]}..${seq_USERS[1]}}"
+done
 
+for USER in $(eval echo ${USERS[@]}); do
+    public_id=sip:${USER}@${DOMAIN}
+    private_id=${USER}@${DOMAIN}
+
+    if [ "$(curl -s http://${HSPROV}/ping 2>&1)" != "OK" ]; then
+	printf "Error: can't contact homestead-prov @ http://${HSPROV}!\n"
+	exit 1
+    fi
+
+    impu=$(curl -s http://${HSPROV}/impu/${public_id} 2>&1)
+    if [[ ${impu:0:1} == "<" ]]; then
+	if [[ "$(curl -s http://${HSPROV}/impi/${private_id}/digest)" =~ digest_ha1 ]]; then
+	    public_id=${public_id}
+
+	    service_profile=$(
+		curl -s -D - http://${HSPROV}/public/${public_id}/service_profile|\
+                grep "Location:"|\
+                awk '{print $2}'|\
+                tr '[[:space:]]' ' '|\
+                sed -e 's#[[:space:]]##g'
+            )
+
+	    new_digest=$(
+		printf "${private_id}:${DOMAIN}:${PASSWORD}"|md5sum|awk '{print $1}'
+	    )
+	    json_digest="{\"digest_ha1\": \"${new_digest}\", \"realm\": \"${DOMAIN}\"}"
+	    put_sta=$(
+		printf "%s\n" "${json_digest}"|\
+                curl -s curl -X PUT -d @- http://${HSPROV}/private/${private_id}
+	    )
+	    if [ ! -z $put_sta ]; then
+		printf "Error: couldn't update password!\n"
+		exit 1
+	    fi
+
+	    if [ $quiet -eq 0 ];then
+		${mydir}/display_user ${USER} ${DOMAIN}
+	    fi
+        else
+	    printf "Error: no IMPI user ${private_id}\n"
+	    exit 1
+	fi
+    else
+        printf "Error: no IMPU user '${public_id}'\n"
+	exit 1
+    fi
+done
