Add configuration sanity checks

diff --git a/homestead.root/usr/share/clearwater/bin/delete_user b/homestead.root/usr/share/clearwater/bin/delete_user
--- a/homestead.root/usr/share/clearwater/bin/delete_user
+++ b/homestead.root/usr/share/clearwater/bin/delete_user
@@ -52,11 +52,13 @@ do
     esac
 done
 
-if [ ! /usr/share/clearwater/homestead/src/metaswitch/crest/local_settings.py ]; then
-    error "Error: missing '/usr/share/clearwater/homestead/src/metaswitch/crest/local_settings.py'"
+local_settings=$(find /usr/share/clearwater/homestead/env -name local_settings.py)
+if [ -z "$local_settings" ]; then
+    printf "Error: can't find local_settings.py!\n"
+    exit 1
 fi
-
-eval $(python -c 'execfile("/usr/share/clearwater/homestead/src/metaswitch/crest/local_settings.py"); print "LOCAL_IP=%s\nHTTP_PORT=%s\n" % (LOCAL_IP, HTTP_PORT)')
+    
+eval $(python -c "execfile(\"$local_settings\"); print \"LOCAL_IP=%s\nHTTP_PORT=%s\nLOCAL_PROVISIONING_ENABLED=%s\nHSS_ENABLED=%s\n\" % (LOCAL_IP, HTTP_PORT, LOCAL_PROVISIONING_ENABLED, HSS_ENABLED)")
 
 if [ -z $LOCAL_IP ]; then
     printf "Error: no LOCAL_IP in local_settings!\n"
@@ -65,6 +67,16 @@ fi
 
 if [ -z $HTTP_PORT ]; then
     printf "Error: no HTTP_PORT in local_settings!\n"
+    exit 1
+fi
+
+if [ "$LOCAL_PROVISIONING_ENABLED" != "True" ]; then
+    printf "Error: local provisioning is not enabled!\n"
+    exit 1
+fi
+
+if [ "$HSS_ENABLED" != "False" ]; then
+    printf "Error: HSS is not disabled!\n"
     exit 1
 fi
 
diff --git a/homestead.root/usr/share/clearwater/bin/display_user b/homestead.root/usr/share/clearwater/bin/display_user
--- a/homestead.root/usr/share/clearwater/bin/display_user
+++ b/homestead.root/usr/share/clearwater/bin/display_user
@@ -52,11 +52,13 @@ do
     esac
 done
 
-if [ ! /usr/share/clearwater/homestead/src/metaswitch/crest/local_settings.py ]; then
-    error "Error: missing '/usr/share/clearwater/homestead/src/metaswitch/crest/local_settings.py'"
+local_settings=$(find /usr/share/clearwater/homestead/env -name local_settings.py)
+if [ -z "$local_settings" ]; then
+    printf "Error: can't find local_settings.py!\n"
+    exit 1
 fi
-
-eval $(python -c 'execfile("/usr/share/clearwater/homestead/src/metaswitch/crest/local_settings.py"); print "LOCAL_IP=%s\nHTTP_PORT=%s\n" % (LOCAL_IP, HTTP_PORT)')
+    
+eval $(python -c "execfile(\"$local_settings\"); print \"LOCAL_IP=%s\nHTTP_PORT=%s\nLOCAL_PROVISIONING_ENABLED=%s\nHSS_ENABLED=%s\n\" % (LOCAL_IP, HTTP_PORT, LOCAL_PROVISIONING_ENABLED, HSS_ENABLED)")
 
 if [ -z $LOCAL_IP ]; then
     printf "Error: no LOCAL_IP in local_settings!\n"
@@ -65,6 +67,16 @@ fi
 
 if [ -z $HTTP_PORT ]; then
     printf "Error: no HTTP_PORT in local_settings!\n"
+    exit 1
+fi
+
+if [ "$LOCAL_PROVISIONING_ENABLED" != "True" ]; then
+    printf "Error: local provisioning is not enabled!\n"
+    exit 1
+fi
+
+if [ "$HSS_ENABLED" != "False" ]; then
+    printf "Error: HSS is not disabled!\n"
     exit 1
 fi
 
@@ -80,21 +92,23 @@ fi
 shift
 
 HSPROV=${LOCAL_IP}:${HTTP_PORT}
+public_id=sip:${USER}@${DOMAIN}
+private_id=${USER}@${DOMAIN}
 
 if [ "$(curl -s http://${HSPROV}/ping 2>&1)" != "OK" ]; then
     printf "Error: can't contact homestead-prov @ http://${HSPROV}!\n"
     exit 1
 fi
 
-impu=$(curl -s http://${HSPROV}/impu/sip:${USER}@${DOMAIN} 2>&1)
+impu=$(curl -s http://${HSPROV}/impu/${public_id} 2>&1)
 if [[ ${impu:0:1} == "<" ]]; then
-    if [[ "$(curl -s http://${HSPROV}/impi/${USER}@${DOMAIN}/digest)" =~ digest_ha1 ]]; then
-	public_id=sip:${USER}@${DOMAIN}
+    if [[ "$(curl -s http://${HSPROV}/impi/${private_id}/digest)" =~ digest_ha1 ]]; then
+	public_id=${public_id}
 
 	service_profile=$(curl -s -D - http://${HSPROV}/public/${public_id}/service_profile|grep "Location:"|awk '{print $2}'|tr '[[:space:]]' ' '|sed -e 's#[[:space:]]##g')
 	iFC=$(curl -s http://${HSPROV}${service_profile}/filter_criteria)
 
-	digest=$(curl -s http://${HSPROV}/impi/${USER}@${DOMAIN}/digest|python -c 'import json,sys;obj=json.load(sys.stdin);print obj["digest_ha1"]' 2>&1)
+	digest=$(curl -s http://${HSPROV}/impi/${private_id}/digest|python -c 'import json,sys;obj=json.load(sys.stdin);print obj["digest_ha1"]' 2>&1)
 
 	echo "HA1 digest:"
         echo "  $digest"
@@ -105,11 +119,11 @@ if [[ ${impu:0:1} == "<" ]]; then
 	    printf "   %s\n" "$line"
 	done
     else
-	printf "Error: no IMPI user ${USER}@${DOMAIN}\n"
+	printf "Error: no IMPI user ${private_id}\n"
 	exit 1
     fi
 else
-    printf "Error: no IMPU user 'sip:${USER}@${DOMAIN}'\n"
+    printf "Error: no IMPU user '${public_id}'\n"
     exit 1
 fi
 
